### ISSUE TITLE
SPNEGO enabled by default after kerberos wizard in HDP3

### ISSUE THREAD

**Issue by kapetre** [HortonworksUniversity/Security_Labs#31]
Looking through the configuration steps in the IPA lab (after inital steps 1-4) - the steps to manually enable spengo should no longer be needed in HDP3.x. https://github.com/HortonworksUniversity/Security_Labs/blob/master/HDP-3.0-IPA.md#enabling-spnego-authentication-for-hadoop 

Unless someone noticed an issue, let's remove instructions to configure those steps manually.

**Comment by abajwa-hw** [comment]
Good point! I had pulled this out of the AD guide but missed this one. Merged in https://github.com/HortonworksUniversity/Security_Labs/commit/04ffa1dde0e743da7b0951442212835ebd621f90
